# Date and Time

## 時間物件、數值表示、文字表示間的關係

在程式語言中，時間通常有三種格式，但就google sheet或EXCEL這種使用者介面而言，他盡量不讓使用者知道有時間物件這個東西，省得徒增困擾，但會允許使用者在數值型態或文字顯示的型態間作切換。不過如果你要從事資料分析，操作時間是非常重要的一個技能，舉凡跟時間軸相關的視覺化或者要限定資料分析的時間區間都常常會用到。其次，值得注意的是，對程式語言的時間來說，`date`和`datetime`前者僅處理日期，後者處理日期+時間，兩者可視資料分析目的互相轉換。

* **時間物件**：一種是該程式語言用來做時間運算的時間物件，Python有Python的時間物件、R有R的時間物件。透過第三方提供的時間計算套件與函式，非常便於計算出日期是第幾週、第幾天、禮拜幾。也可以兩個時間相減來產生時間差。
* **時間字串**：另一種是該時間物件可以被展示為字串。用API可以存取的時間，或者說資料紀錄的時間欄位，多半是文字。不過文字狀態的時間沒辦法被運算（就文字而已，要怎麼做運算？），所以通常程式語言必須要將其轉換為該語言特有的時間物件。爬蟲所爬下來的幾乎都是文字型態，必須要自己根據文字的表示內容轉換為時間物件才可以做運算。
* **時間的整數表示**：時間在電腦上被實作的方式實際上是整數或小數，而軟體工程師會把該整數用數學公式轉為時間（例如用自1900年1月1日0分0秒至今日的總秒數的整數來作為時間的儲存單位）。一般來說，系統在輸出資料時所自動吐出來的時間普遍是用整數來記錄，所以如果你處理的是瀏覽器所吐出來的時間，那大概是整數。以Google sheet來說，其基準點是1900年1月1日0分0秒，如果是Date，就是這個基準加上一串整數。如果是時間，就是這個基準加上一串帶小數點的整數，而儲存在電腦裡，就是上述的整數，或者是帶小數點的整數（Numeric）

在**datatime**資料在網路上交換時，通常用文字型態或數值型態。例如*twitter API*和*facebook graph API*所下載的資料時間型態都是文字，PTT等用爬蟲爬下來的更是文字。但部分由API或者資料庫查詢回來的結果可能是數值；Excel若把某個變數指定為時間的話，那下載下來該變數也會是數值型態，需要自己寫程式進行轉換。因此，處理時間資料的第一件事情就是要知道他的時間是什麼格式。再來，通常每個程式語言都會有自己的時間物件，並且定義好一系列的轉換函式，讓寫程式的人將文字型態或數值型態的時間轉換為該語言所獨有的時間物件，或將時間物件轉回文字或數值型態。我們在寫R時，會用第三方所開發的*lubridate*套件來處理時間。

時間的常用操作概略有以下幾項：
1. 字串轉時間物件
2. 數值轉時間物件
3. 取週、月、或年為分析單位




