## 自述 {-}

2016年有幸可以到臺灣大學新聞所帶領一群未來的記者學習資料分析的技巧。說是資料分析，不如說是程式設計。當時紐約時報、國際上各大報紙大量地產製資料新聞，嘗試用資料搭配視覺化來敘事，或者透過資料探勘方法，挖掘數字、資料背後的異常現象、趨勢、分佈等等。

為了兼顧每一位學生的學習情形，特地採用小班教學，但卻有不少外系的學生也一起到課堂上來學習，因而以每個學期開課、每堂課最多三十人的模式授課。這樣頻繁授課的好處是，可以反覆地、快速地嘗試各種不同的授課方式，並且在次學期授課中進行調整。而這本書則是在授課過程零星所記錄下來的經驗和知識。

2016年開始在臺大教書的那個暑假，我其實擅長的程式語言是Python，且有二至三年開授「社會科學程式設計:ProgrammingforSocialScience」的經驗。但到任前單位主管希望我能夠以R為主要授課語言，單位主管和紐約時報的圖表編輯部門有數年的互動，她告訴我紐約時報圖表記者們都用R語言。而在2016年的當時，北臺灣業界和研究單位所開授的網路爬蟲、資料分析、機器學習等課程，都是以R為主要語言。顯然當時以Python為主要語言的「深度學習」族群尚未在臺灣發展起來(在2018年的現在，也就是我寫下這句話之時，其實臺灣熱門的是Python程式語言)。

那年暑假，我用了Datacamp來產生我對R語言的基礎認識、聽了二至三門Coursera上的R語言課程來了解R語言的授課方式、參考了三至四份以R為語言的國外課程教材、甚至自費參與由臺灣業界一群熱心的工程師所開發的網路爬蟲課程、與當時臺灣資料科學年會所開發的「手把手教你資料分析」課程觀摩他人上課的節奏和使用範例，我非常感謝有這群先行者的努力和無私的分享，讓我在後續的課程安排上駕輕就熟。

在2016年國外所開設以R來進行資料分析的課程也不算多，但在2018年的今日，Stanford的PoliticalScience與Chicago的MasterofComputationalSocialScience均開設了質量非常高的R在社會科學應用上的課程，Stanford的PoliticalScience甚至將其拆解為150A、150B、150C三門課程來授課。

基於這樣的出發點，所以這本書的核心對象就是從沒有寫過程式的大學生。



## 學程式這回事 {-}

### 何謂演算法？ {-}

演算法（Algorithm）為處理事情、解決問題的邏輯，多取自日常生活的問題解決步驟。例如Google用以排名搜尋結果的「PageRanking」即參考自人與人之間，如何透過每次的訊息交換，建立起人的聲望。而推薦機制的核心概念「協同式推薦」，則仿自市集群眾購物行為的共同喜好、熱門物品等機制。
而程式語言（ProgrammingLanguage）則是演算法的實作。定義一套機器能夠編譯的語法，將演算法實作出來。脫離程式語法的演算法也可以被英文邏輯性地加以表徵，被稱之為「Pseudo-code」。一段典型的Pseudo-code如下，描述了ATM提款機如何提款與存款的決策步驟。

```
Ifoption=depositthen
Output'Enteramounttodeposit'
Inputamount
balance=balance+amount
Ifoption=withdrawalthen
Output'Enteramounttowithdraw'
Inputamount
balance=balance-amount
Output'Balanceis'balance
```

因此，程式語言的學習，則類似將日常生活的處事方法，用正確的邏輯方式來表達，並用一種指定的語言來描述。準此，程式語言的學習是「語言與邏輯」。而回想我們如何學會英文或者有天突然覺得自己將英文的運用推到另一個層次之上時，往往有一番自己的方法和領會，多半來自於個人目標與適合個人的學習方法，例如，考TOEIC、TOFEL、GRE，看美國影集、看英文原版小說，或者為了打電玩。

### 掌握課外學習資源 {-}

現在網路上自學資源非常多，尤其是各家線上開放課程，或者是code.org、Datacamp等線上互動學習平台，所以我在授課的過程，我多半是在課堂上強調程式語言中的關鍵技術、使用方法、使用時機和比較彼此間的差異，我甚少把一個概念和各種可用的函式在課堂上講完全，反而建議學生可以透過買書、上線上的課程來相互補充。我那時衍生了一個口頭禪是「聽一次聽不懂」


