# Data Journalism

## What-is 什麼是資料新聞？

我其實很少在談論何謂資料新聞，或者為他下定義。但我還蠻喜歡一位台籍資料新聞記者林辰峰在某一次受邀回國演講後所講的一段動機。

> 想像你是一名記者，一名追求事實，挖掘真相的記者。你對政治獻金相關議題很有興趣，做訪前研究時，發現網路上有多筆龐大政治獻金數據。你盯著電腦螢幕，看著眼前一筆又一筆的數據。你順手點了滑鼠右鍵，希望下載這份資料庫，卻發現網頁不開放右鍵下載。「或許我應該將這些數據一筆一筆抄下來。」你或許會這樣告訴自己。無奈數據共有數萬筆，書手抄寫容易犯錯又耗時。你單手托腮，無奈地嘆了一口氣。你肯定新聞就藏在這些數據裡，但卻不知該如何是好。文章來源：
https://www.twreporter.org/a/opinion-data-journalist 

接著，我們可以從一些資料新聞的案例，來看看何謂資料新聞。
1. [Melissa Etehad & Jeremy C.F. Lin (2016-08-13). The world is getting better at paid maternity leave. The U.S. is not. The Washington Post.](https://www.washingtonpost.com/news/worldviews/wp/2016/08/13/the-world-is-getting-better-at-paid-maternity-leave-the-u-s-is-not/?noredirect=on&utm_term=.8ce417321dc7
)。這篇的第二作者即為前述所提到的林辰峰（Jeremy Lin），他當時人在華盛頓郵報。
2. [田孟心（2016-12-15）。頂加房子租多貴？天下雜誌。](https://www.cw.com.tw/article/article.action?id=5079941)。這位作者是現在的天下雜誌記者，當時他與另一位天下的資料新聞記者林佳賢一起維護Dataman這個臉書粉絲團。那應該是該記者剛接觸資料分析和程式設計的第一年。
3. [邱學慈（2019-01-08）。PTT原始資料全揭露！「韓流」怎麼造出來的？天下雜誌](https://www.cw.com.tw/article/article.action?id=5093610)。 大約在2018年暑假的時候邱學慈才剛利用暑期課程學完R，之後在下學期便修了台大新聞所Adrian教授的社會網絡分析課程，便延伸在天下做了這樣的作品。

其實從這些例子的時間大概可看到，學習程式只是一種用來處理資料的功夫，你也可以用EXCEL或者Google sheet來處理資料，只要你能夠處理這些資料，那我想你就有辦法寫作資料新聞。所以我比較傾向於前述林辰峰的說法，資料新聞的開始是一種從資料中發掘事實的動機。如果你有那個動機，那大概過程的技術問題你都會去克服；相反的如果沒有那個動機，那大概學了程式也不知道能夠做什麼。

## 何謂資料？
並不是所有人所認定的「資料」的概念都是相同的，比方來說，從網路上可獲得有觀察值和統計資料兩大種。

1. **觀察值（Observation）**：每一列就是一次的觀察，比方說紀錄所有登革熱案例的發生地點、鄰里，或是空氣品質資料測站的歷史紀錄、或是紀錄PTT上面誰曾經回應過誰、或是臉書上的競選廣告資料（花多少錢、打什麼年齡層、打多久）也是屬於觀察值資料。這種觀察值資料不多，多半出現在輿論資料或者新聞資料等尚未彙整過的資料。未彙整的資料多半資料量龐大，很少用開放資料的方式被分享。這類紀錄資料通常要進一步進行彙整才能夠繪圖或者做分析。在[登革熱近12個月每日確定病例統計](http://data.gov.tw/node/21026)的資料中，就字面上看來是統計資料，但實際上資料是一筆一筆紀錄每個案例的狀況，所以應該是觀察值資料，而非統計資料，這標題有「統計」兩個字不太恰當。
2. **統計資料**：指的是該資料呈現的是根據某個或者某幾個變數所計數（counting）的資料，是最常見的資料。例如台北市每小時在每個區有多少竊盜案、逐年的死因統計資料、內政部的各縣市鄉鎮的性別、教育程度、婚姻狀況的人口數。


統計資料有幾種不同的情形會攸關資料分析能夠發揮的程度。大概分成一下幾種情形：
1. **資料是比例資料**: 比例資料是資料分析上最不樂見的資料型態，會使得資料完全無法結合其他的資料表。偏偏很多政府單位開放出來是這種型態，例如各地區的女警比例、大專院校教務會議的女性成員比例。不過有些比例資料是有意義的，例如逐週醫療院所的類流感就診所佔比例，可以知道來看病的病人中大概有多少比例是有流感症狀的，這可以代表流感流行的嚴重程度。
2. **資料是平均過後的資料**：通常這類的資料難以結合其他的資料進行加工。但ETC的資料就是這類的資料，他每五分鐘就紀錄了一個路段的大客車數以及其平均速率。
3. **資料已經被做成二維的資料表**：通常我們會希望，每一個欄就是一個變數，例如性別、年齡組、婚姻狀況、教育程度等等，都是一個直欄上的變數。但有時候政府公布的資料已經是產製成該單位的年度報告或新聞資訊的報告圖表了，所以會是以兩個變項分別在欄與列的方式來呈現。例如性別x年齡組的表格、婚姻狀況x教育程度的表格。這類資料經常缺少基本單位，例如「鄉鎮市區」或者「時間區間」等等。


## 資料的詮釋

記者在做的事情顯然就是在詮釋資料。這篇文章的作者提供了數個例子來教我們資料詮釋時可能會產生的謬誤。
[Kate Crawford (2013) The Hidden Biases in Big Data](https://hbr.org/2013/04/the-hidden-biases-in-big-data)

Crawford（2013）一文曾提及使用資料分析可能帶來的謬誤。例如當Sandy颱風侵襲美東時，有研究在蒐集Twitter的資料後發現，如預期中雜貨店的購物行為提升，但非預期中地，夜生活卻在颱風來襲後增多，也許是cabin fever strikes。但該篇報導認為這樣的資料大多蒐集自曼哈頓，顯然不是嚴重受到侵襲的區域。他認為「Data are assumed to accurately reflect the social world, but there are significant gaps, with little or no signal coming from particular communities.」

他舉了另外一個例子是，Boston設計了一個StreetBump smartphone app，透過偵測手機的震動來知道哪一些路段有洞。但這篇文章認為，有些有數位落差的區域，尤其是老人，顯然會因此偏重在那些具有數位資源的區域misallocating important public resources。這也沒錯，但現在手機上看報紙那麼方便，到處都沒電話亭，這樣就有處理了數位落差的問題嗎？

他又舉了Google Trend預測流感為例，比CDC整整高估了兩倍，雖然可以解釋說，Google上面的media coverage導致重複資訊不斷出現，但他認為這樣做可能會造成政府錯估疫情？這我也覺得很妙，看疫情是看趨勢，CDC說的6%也不見得對，說不定還有潛藏疫情，不知道為何要用一種為了打資料科學而雞蛋裡挑骨頭的毛病來寫作？作者提到，政府可能會因為這樣而產生資源分配不均，但我認為這三個例子到資源分配的決策都還非常遙遠。

基本上，「資料的詮釋」通常只能反映出記者或研究者本身對某個事件或現象的詮釋角度。資料詮釋所反映的不是真實，也不是社會現實。我們在過去的經驗中，經常可以發現從資料或視覺化的操弄，往往可以讓使用者迷失焦點，甚至獲得完全相反方向的結果。因此，詮釋時其實經常陷於報導與資料的兩難，經常遇到資料量過度稀少，即使要說明一個現象，證據數量不夠、說服力不夠。但，所幸新聞是一個即使是少數樣本亦值得說明其狀況的文本，專注說明資料的outlier，也許就是所謂「新聞點」的產生地。唯一要記得的是，不可把少數人的現象過分推論到整個母體或群體，這是資料新聞寫作上常犯的錯誤。

## Where-is data? 資料在哪裡？

```{exercise name="Where is data?"}
請問在Alexa網站流量調查「Top Sites in Taiwan」所列的Top 100網站中，哪些網站可能具有資料分析價值？或者哪些網站可能具有新聞價值？
```

## What does data look like?

由於R其實是一個**統計軟體**，因此對於怎麼操作它，只要有一點統計的思維就會非常容易入屎。簡單地說，就是用**變項（Variable）**來想像所有的資料。對普遍的資料而言，橫列（Row）就是資料項，直欄（Column）就是變項欄。對於部分自認為統計都快忘光的初學者，直接用R來思考很容易有熟悉感；對於完全沒統計基礎的初學者，則建議用資料表（如Microsoft Excel或Google sheet）來想像它。
